/**
 * Extracts timestamp from a request ID (if generated by this utility)
 */
export function extractTimestampFromRequestId(
  requestId: string,
  prefix?: string,
): Date | null {
  const match = requestId.match(
    new RegExp(`^${prefix ? `${prefix}_` : ''}(\\d+)_[a-f0-9]{8}$`),
  );
  if (match) {
    return new Date(parseInt(match[1], 10));
  }
  return null;
}
