/**
 * Extracts timestamp from a request ID generated by generateRequestId.
 *
 * Parses request IDs with format: `[prefix_]timestamp_randomhex`
 * Returns null if the ID doesn't match the expected format.
 * @param requestId - Request ID string to parse
 * @param prefix - Optional prefix that was used during generation
 * @returns Date object representing the timestamp, or null if format doesn't match
 * @public
 */
export function extractTimestampFromRequestId(requestId: string, prefix?: string): Date | null {
  const match = requestId.match(new RegExp(`^${prefix ? `${prefix}_` : ''}(\\d+)_[a-f0-9]{8}$`));
  if (match) {
    return new Date(parseInt(match[1], 10));
  }
  return null;
}
