import { randomBytes } from 'crypto';

/**
 * Extracts timestamp from a request ID (if generated by this utility)
 */
export function generateRequestId(prefix?: string): string {
  const timestamp = Date.now();
  const randomSuffix = randomBytes(4).toString('hex');
  return `${prefix ? `${prefix}_` : ''}${timestamp}_${randomSuffix}`;
}
