/**
 * Validates that a request ID matches the format generated by generateRequestId.
 *
 * Checks for format: `[prefix_]timestamp_randomhex` where timestamp is digits
 * and randomhex is exactly 8 hexadecimal characters.
 * @param requestId - Request ID string to validate
 * @param prefix - Optional prefix that should be present in the ID
 * @returns True if the ID matches the expected format
 * @public
 * @see {@link generateRequestId} - Function that generates IDs validated by this function
 */
export function isValidRequestId(requestId: string, prefix?: string): boolean {
  return new RegExp(`^${prefix ? `${prefix}_` : ''}\\d+_[a-f0-9]{8}$`).test(
    requestId,
  );
}
